#!/usr/bin/env bash 
# Show information about domain and subdomains and their IP's

infodomain()
{
    ip_output=$(dig "$2.$1" | grep -A1 'ANSWER SECTION:' | tail -n1)
    # ip_output is the output of dig and $1 is the subdomain, which is used in awk as $6
    echo "$ip_output $2" | awk '{ print "The subdomain " $6 " is a " $4 " record and points to " $5 }'
}

if [ "$#" -eq 1 ]
then
    infodomain $1 "www"
    infodomain $1 "lb-01"
    infodomain $1 "web-01"
    infodomain $1 "web-02"
elif [ "$#" -gt 1 ]
then
    infodomain $1 $2
fi
