#!/usr/bin/env bash
# Install nginx on a web server on port 80
sudo apt-get update
sudo apt-get install -y nginx
# read a string from std input and write to std output and index file
echo "Holberton School my people" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
