#!/usr/bin/env bash
# install load balancer and use it with roundrobin
sudo apt-get update
sudo apt-get install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get install -y haproxy
# Get permissions to edit haproxy
sudo chmod 777 /etc/default/haproxy
# We need to enable HAProxy to be started by the init script.
echo "ENABLED=1" >> /etc/default/haproxy
# Frontend settings
front="\n
frontend Local_Server  
\tbind *:80                                                                                                                                                                                              
\tmode http
\tdefault_backend backendnodes"
back="\n
backend Local_Server
\tbalance roundrobin
\tserver 1198-web-01 34.74.97.226:80 check
\tserver 1198-web-02 18.209.18.155:80 check"
sudo echo -e "$front" >> /etc/haproxy/haproxy.cfg
sudo echo -e "$back" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
