#!/usr/bin/env bash
# This script display "Holberton School" 10 times
string="Holberton School"
counter=1
while [ $counter -le 10 ]
do
    echo "$string"
    if [ $counter -eq 9 ]
    then
	echo "Hi"
    fi
    ((counter++))
done
