#!/usr/bin/env bash
# This script display "Holberton School" 10 times
string="Holberton School"
counter=1
while [ $counter -le 10 ]
do
    if [ $counter -eq 4 ]
    then
	echo "bad luck"
    elif [ $counter -eq 8 ]
    then
	echo "good luck"
    else
	echo "$string"
    fi
    ((counter++))
done
