#!/usr/bin/env bash
# Change nginx default user to nginx and listening port
# Kill apache listening poty
sudo pkill apache2
# Set nginx 8080 port
sudo sed -i 's/80 default/8080 default/' /etc/nginx/sites-enabled/default
# Give access and owner to nginx.conf when sudo -u is executed
sudo chown nginx /etc/nginx/nginx.conf
sudo chmod 700 /etc/nginx/nginx.conf
# execute command as nginx user
sudo -u nginx service nginx restart
