#!/usr/bin/env bash
# Change nginx default user to nginx and listening port
sudo pkill apache2
sudo sed -i 's/80 default/8080 default/' /etc/nginx/sites-enabled/default
sudo chown nginx /etc/nginx/nginx.conf
sudo chmod 700 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
